version: '3.8'

services:
  app:
    image: contact-form-server
    build:
      context: .
    ports:
      - '3099:3099'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
